### ISSUE TITLE
Issues loading GPXs into Basecamp

### ISSUE THREAD

**Issue by nikcster** [lonvia/waymarked-trails-site#268] opened 2017-05-23 12:11 UTC
Hi

I downloaded some NCN routes (the one below is 76) and loaded them up in Basecamp but in some cases the routes are all over the place. Any idea what I'm doing wrong?

![image](https://cloud.githubusercontent.com/assets/19348996/26353615/30208886-3fb9-11e7-8832-d663fdc1d6b6.png)

Ta.
Nick.

**Comment by lonvia** [comment] 2017-05-24 22:35
That is a know issue. The segments in the GPX are not ordered but Basecamp tries to connect them anyways. There is some code to improve on the ordering already but it is not yet enabled due to some bug.

Duplicate of #2.

**Closed by lonvia** 2017-05-24 22:35 UTC
